name: Ping Render to keep it awake

on:
  schedule:
    - cron: '*/10 * * * *' # every 10 minutes (UTC)
  workflow_dispatch: # allows manual runs

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping health endpoint
        run: |
          set -e
          curl -sS -m 15 -o /dev/null -w "%{http_code}\n" "$RENDER_HEALTH_URL" | tee /tmp/status
          code=$(cat /tmp/status)
          echo "HTTP $code"
          test "$code" -ge 200 -a "$code" -lt 400
    env:
      RENDER_HEALTH_URL: ${{ secrets.RENDER_HEALTH_URL }}
